#!/usr/bin/env python3

import sys
from optparse import OptionParser

from resources.check import do_checks

if __name__ == "__main__":
    parser = OptionParser()
    parser.add_option("-s", "--sourcedir", dest="src",
                      help="Use files in DIR as input files. Default: ../icvpn-meta/",
                      metavar="DIR",
                      default="../icvpn-meta/")

    (options, args) = parser.parse_args()

    ret = do_checks(options.src)

    sys.exit(ret)
