#!/usr/bin/env python3
"""
findfree - find free resources in the icvpn meta universe
"""
import argparse

from resources.findfree import find

if __name__ == "__main__":
    PARSER = argparse.ArgumentParser(
        description="Find free resources in the Freifunk ICVPN Universe",
        epilog="Make sure your copy of icvpn-meta is up to date, to ensure "
               "this utility produces useful results.")

    PARSER.add_argument('-s', '--source-dir',
                        metavar='DIRECTORY', dest='src',
                        default='../icvpn-meta/',
                        help="path to the local copy of the icvpn-meta"
                             "repository (Default: ../icvpn-meta/)")
    PARSER.add_argument('-p', '--prefix-length',
                        type=int, default=20,
                        metavar='PREFIX', dest='required_prefix_len',
                        help="Required prefix length (Default: 16)")
    PARSER.add_argument('-c', '--count',
                        type=int, default=5,
                        metavar='COUNT', dest='option_count',
                        help="The amount of options to show (Default: 5)")

    ARGS = PARSER.parse_args()

    find(ARGS.src, ARGS.required_prefix_len, ARGS.option_count)
