#!/usr/bin/env python3

from argparse import ArgumentParser

import resources.roa

if __name__ == '__main__':
    formatters = {
        'bird': resources.roa.BirdRoaFormatter,
    }

    PARSER = ArgumentParser()
    PARSER.add_argument('-f', '--format', dest='fmt',
                        help='Create config in format FMT. Possible values: {formatters}.'.format(
                                formatters=", ".join(formatters.keys())),
                        metavar='FMT',
                        choices=list(formatters.keys()),
                        default='bird')
    PARSER.add_argument('-4', dest='family', action='store_const', const='ipv4',
                        help='Generate IPv4 config')
    PARSER.add_argument('-6', dest='family', action='store_const', const='ipv6',
                        help='Generate IPv6 config')
    PARSER.add_argument('-s', '--sourcedir', dest='src',
                        help="Use files in DIR as input files. Default: ../icvpn-meta/",
                        metavar="DIR", default="../icvpn-meta/")
    PARSER.add_argument('-x', '--exclude', dest='exclude', action='append',
                        help='Exclude the comma-separated list of COMMUNITIES',
                        metavar='COMMUNITIES',
                        default=[])
    PARSER.add_argument('-m', '--max', dest='default_max_prefixlen', default=None,
                        type=int, help='max prefix length to accept')
    PARSER.set_defaults(family='ipv6')

    ARGS = PARSER.parse_args()

    resources.roa.create_config(ARGS.src, set(ARGS.exclude),
                                ARGS.family, formatters[ARGS.fmt],
                                ARGS.default_max_prefixlen)
