#!/usr/bin/env python3

from argparse import ArgumentParser

import resources.smokeping

if __name__ == '__main__':
    formatters = {
        'SmokePing': resources.smokeping.SmokePingFormatter,
    }

    PARSER = ArgumentParser()
    PARSER.add_argument('-f', '--format', dest='fmt',
                        help='Create config in format FMT. Possible values: {formatters}. '
                             'Default: SmokePing'.format(formatters=", ".join(formatters.keys())),
                        metavar='FMT',
                        choices=list(formatters.keys()),
                        default='SmokePing')
    PARSER.add_argument('-s', '--sourcedir', dest='src',
                        help='Use files in DIR as input files. Default: ../icvpn-meta/',
                        metavar='DIR',
                        default='../icvpn-meta/')
    PARSER.add_argument('-x', '--exclude', dest='exclude', action='append',
                        help='Exclude the comma-separated list of COMMUNITIES',
                        metavar='COMMUNITIES',
                        default=[])

    ARGS = PARSER.parse_args()

    resources.smokeping.create_config(ARGS.src, set(ARGS.exclude), formatters[ARGS.fmt])
