#!/usr/bin/env python3

from argparse import ArgumentParser

import resources.table

if __name__ == '__main__':
    PARSER = ArgumentParser()
    PARSER.add_argument('-s', '--sourcedir', dest='src',
                        help='Use files in DIR as input files. Default: ../icvpn-meta/',
                        metavar='DIR', default='../icvpn-meta/')

    ARGS = PARSER.parse_args()

    resources.table.mktable(ARGS.src)
